### ISSUE TITLE
I'M Getting an error message when i try to push my code online

### ISSUE THREAD

**Issue by Blesszo** [Ajuatah/Dart-Programming#14]
> git push -u origin1 AddNumbersInArray
To https://github.com/Ajuatah/Dart-Programming.git
 ! [rejected]        AddNumbersInArray -> AddNumbersInArray (non-fast-forward)
error: failed to push some refs to 'https://github.com/Ajuatah/Dart-Programming.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Ajuatah** [comment]
> > git push -u origin1 AddNumbersInArray
> > To https://github.com/Ajuatah/Dart-Programming.git
> > ! [rejected]        AddNumbersInArray -> AddNumbersInArray (non-fast-forward)
> > error: failed to push some refs to 'https://github.com/Ajuatah/Dart-Programming.git'
> > hint: Updates were rejected because the tip of your current branch is behind
> > hint: its remote counterpart. Integrate the remote changes (e.g.
> > hint: 'git pull ...') before pushing again.
> > hint: See the 'Note about fast-forwards' in 'git push --help' for details.

you are following the wrong steps to push the code

**Comment by Dhruvilsarvadhi** [comment]
[](https://stackoverflow.com/questions/35077787/git-push-not-working-no-error)

you are following this Link

**Comment by Dhruvilsarvadhi** [comment]
you are following this Link[](https://stackoverflow.com/questions/35077787/git-push-not-working-no-error)

**Comment by Ajuatah** [comment]
use this "git pull origin master" better still since you want to push to  AddNumbersInArray branch you can do this command first before you do a push "git pull  origin AddNumbersInArray" .

**Comment by Blesszo** [comment]
Ok, thank you sir .

Tenjoh Bless,
-------------------------------------------
2019 to 2022 Community service leader|meter quarter|
Member of Open Field.
--
Tel/WhatsApp:+237678208585
email: ***@***.***
Facebook:https://www.facebook.com/profile.php?id=100068840171307

Twitter::https://twitter.com/Blesszo12?t=jxQIMyMW_3pv3OpvZlwPxw&s=09

LinkedIn::https://www.linkedin.com/in/tenjoh-bless-b343a1255
